import {readFile,lstat} from 'node:fs/promises';
import {selectAccount,type Account,type Config} from '../config.js';
import {BufferError,UsageError} from './errors.js';
export type Json=Record<string,any>;
export class BufferClient{
 private tokens=new Map<string,string>();private schedules=new Map<string,Promise<void>>();private nextAt=new Map<string,number>();
 constructor(readonly config:Config,private readonly fetcher:typeof fetch=fetch,private readonly sleep:(ms:number)=>Promise<void>=ms=>new Promise(r=>setTimeout(r,ms))){}
 redactText(text:string):string{for(const s of [...this.config.accounts.map(a=>a.apiToken),...this.tokens.values()].filter(Boolean).sort((a,b)=>b.length-a.length))text=text.split(s).join('[redacted]');return text;}
 sanitize(value:unknown):unknown{if(typeof value==='string')return this.redactText(value).replace(/https?:\/\/[^\s"<>]*(?:X-Amz-Signature|[?&](?:token|signature|sig|key|access_token)=)[^\s"<>]*/gi,'[private credential URL]');if(Array.isArray(value))return value.map(v=>this.sanitize(v));if(value&&typeof value==='object')return Object.fromEntries(Object.entries(value).map(([k,v])=>[k,/^(password|secret|api_token|api_key|token|access_token|refresh_token|cookie|cookies|authorization)$/i.test(k)?'[redacted]':this.sanitize(v)]));return value;}
 private async token(a:Account):Promise<string>{if(this.tokens.has(a.name))return this.tokens.get(a.name)!;let token=a.apiToken;if(a.tokenFile)try{const s=await lstat(a.tokenFile);if(!s.isFile()||s.size>65536||(process.platform!=='win32'&&(s.mode&0o077)))throw Error();token=(await readFile(a.tokenFile,'utf8')).trim();}catch{throw new BufferError('Cannot read the private Buffer token file; use a regular owner-only token file, at most 64 KB.',0,'CONFIG');}if(!token||/[\r\n]/.test(token))throw new BufferError('No valid API token configured for the selected account. Run buffer-cli login.',0,'CONFIG');this.tokens.set(a.name,token);return token;}
 private async pace(a:Account):Promise<void>{const prev=this.schedules.get(a.name)??Promise.resolve();const next=prev.catch(()=>{}).then(async()=>{const delay=Math.max(0,(this.nextAt.get(a.name)??0)-Date.now());if(delay)await this.sleep(delay);this.nextAt.set(a.name,Date.now()+this.config.minIntervalMs);});this.schedules.set(a.name,next);await next;}
 async request(query:string,variables:Json={},accountHint?:string):Promise<Json>{const a=selectAccount(this.config,accountHint);const body=JSON.stringify({query,variables});if(Buffer.byteLength(body)>1024*1024)throw new UsageError('Request JSON exceeds the 1 MiB local cap.');const token=await this.token(a);await this.pace(a);let response:Response;try{response=await this.fetcher('https://api.buffer.com',{method:'POST',redirect:'error',signal:AbortSignal.timeout(this.config.timeoutMs),headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json',Accept:'application/json'},body});}catch{throw new BufferError('Buffer request failed or timed out. No automatic retry was made; verify the account before repeating any mutation.',0,'NETWORK_ERROR');}
 const reader=response.body?.getReader();let total=0;const chunks:Uint8Array[]=[];if(reader)try{while(true){const {done,value}=await reader.read();if(done)break;total+=value.byteLength;if(total>5*1024*1024){await reader.cancel();throw new BufferError('Buffer response exceeds the 5 MiB local cap.',response.status,'RESPONSE_LIMIT');}chunks.push(value);}}finally{reader.releaseLock();}
 if(!response.ok)throw new BufferError(`Buffer HTTP ${response.status}; no automatic retry was made.`,response.status,response.status===429?'RATE_LIMIT_EXCEEDED':'HTTP_ERROR');let result:Json;try{result=JSON.parse(Buffer.concat(chunks).toString('utf8'));if(!result||typeof result!=='object'||Array.isArray(result))throw Error();}catch{throw new BufferError('Buffer returned an invalid JSON response.',response.status,'INVALID_RESPONSE');}
 if(Array.isArray(result.errors)&&result.errors.length){const error=result.errors[0];const code=String(error.extensions?.code??'GRAPHQL_ERROR');throw new BufferError(this.redactText(`${code}: ${String(error.message??'Buffer GraphQL request failed.')}`),response.status,code);}
 if(!result.data||typeof result.data!=='object')throw new BufferError('Buffer returned no GraphQL data.',response.status,'INVALID_RESPONSE');
 for(const item of Object.values(result.data) as Json[]){if(item&&typeof item==='object'&&typeof item.__typename==='string'&&/Error$/.test(item.__typename))throw new BufferError(this.redactText(`${item.__typename}: ${String(item.message??'Buffer mutation failed.')}`),response.status,item.__typename);}
 return {data:this.sanitize(result.data),rateLimit:this.sanitize(response.headers.get('ratelimit')??null),retryAfter:this.sanitize(response.headers.get('retry-after')??null)};
 }
}
