import operationsData from './operations.json' with {type:'json'};
import {Ajv2020} from 'ajv/dist/2020.js';import type {ValidateFunction} from 'ajv';
import {parse,print,Kind,type FieldNode,type SelectionSetNode,type DocumentNode,type OperationDefinitionNode} from 'graphql';
import {renderSelections,collectAllPaths} from '../vendor/buffer-selections.mjs';
import {readFile,lstat} from 'node:fs/promises';
import {UsageError,BufferError} from '../api/errors.js';import type {BufferClient,Json} from '../api/client.js';import {selectAccount,type Config} from '../config.js';import type {Risk} from '../safety.js';
export type ToolSpec={name:string;title:string;description:string;group:string;inputSchema:Json;risk:Risk;handler:(args:Json,client:BufferClient)=>Promise<unknown>};
export type Operation=Json&{fieldName:string;operationType:'query'|'mutation';jsonInputSchema?:Json;operationShell:string;defaultFields:string[];selectionTree:any;pagination?:{pageSizeArg:string;cursorArg:string;defaultPageSize:number};resultAccess:Json;variableMappings:Json[]};
export const OPERATIONS=operationsData as unknown as Operation[];
const ajv=new Ajv2020({allErrors:true,strict:false});
function strictSchema(v:Json):Json{const x=structuredClone(v);function walk(s:Json){if(s.type==='object'&&s.properties){s.additionalProperties=false;for(const p of Object.values(s.properties) as Json[])walk(p);}if(s.items)walk(s.items);for(const k of ['anyOf','oneOf','allOf'])for(const child of s[k]??[])walk(child);}walk(x);return x;}
const inputValidators=new Map(OPERATIONS.map(o=>[o.fieldName,ajv.compile(strictSchema(o.jsonInputSchema??{type:'object',properties:{}}))]));
function check(v:ValidateFunction,a:unknown):void{if(!v(a))throw new UsageError(ajv.errorsText(v.errors,{separator:'; '}));}
export function toolName(o:Operation):string{return (o.operationType==='query'?'get_':'')+o.fieldName.replace(/[A-Z]/g,c=>'_'+c.toLowerCase());}
const accountSchema={type:'string',minLength:1,description:'Private account profile name. Selects credentials only; an organization default does not restrict provider token permissions.'};
const fieldsSchema={type:'array',items:{type:'string',minLength:1,maxLength:200},minItems:1,maxItems:100,description:'Upstream field paths relative to the result, as in official CLI --fields. Default fields are bounded. Use items.id for connection nodes; pageInfo.endCursor for cursors.'};
const confirmSchema={type:'boolean',description:'Must be true for this exact user-requested Buffer mutation.'};
function propertiesFor(o:Operation):Json{const props:Json={...(strictSchema(o.jsonInputSchema??{}).properties??{}),payload:{...strictSchema(o.jsonInputSchema??{type:'object',properties:{}}),description:'Complete native input object instead of individual input fields.'},payload_file:{type:'string',minLength:1,description:'Regular local JSON input file, no symlink, at most 1 MiB; cannot mix with payload or individual input fields.'},fields:fieldsSchema,account:accountSchema};if(o.pagination){props.first={type:'integer',minimum:1,maximum:100,description:'Local page-size cap 100, default 25; provider may impose additional query limits.'};props.after={type:'string',maxLength:8192,description:'Opaque cursor from pageInfo.endCursor. One page per ordinary call.'};}if(o.operationType==='mutation')props.confirm=confirmSchema;return props;}
async function nativeInput(o:Operation,args:Json,client:BufferClient,preview=false):Promise<Json>{const flat=Object.fromEntries(Object.keys(o.jsonInputSchema?.properties??{}).filter(k=>args[k]!==undefined).map(k=>[k,args[k]]));if((args.payload!==undefined||args.payload_file!==undefined)&&Object.keys(flat).length)throw new UsageError('Use input fields or payload/payload_file without mixing them.');if(args.payload!==undefined&&args.payload_file!==undefined)throw new UsageError('Use payload or payload_file, not both.');let input:Json=args.payload??flat;if(args.payload_file)try{const st=await lstat(args.payload_file);if(!st.isFile()||st.size>1024*1024)throw Error();input=JSON.parse(await readFile(args.payload_file,'utf8'));}catch{throw new UsageError('payload_file must be a regular JSON input file at most 1 MiB.');}
 input=structuredClone(input);if(o.jsonInputSchema?.properties?.organizationId&&input.organizationId===undefined&&!preview){const account=selectAccount(client.config,args.account);if(account.organizationId)input.organizationId=account.organizationId;}
 check(inputValidators.get(o.fieldName)!,input);return input;}
export async function prepare(o:Operation,args:Json,client:BufferClient,preview=false):Promise<{document:string;variables:Json}>{const input=await nativeInput(o,args,client,preview);const fields=args.fields??o.defaultFields;if(!Array.isArray(fields)||fields.length<1||fields.length>100||fields.some((v:any)=>typeof v!=='string'||v==='all'||v.length>200))throw new UsageError('fields must contain 1–100 explicit field paths; unbounded all is disabled.');const rendered=renderSelections(o.selectionTree,fields);if(rendered.unknownPaths.length||!rendered.selections.trim())throw new UsageError('Unknown or empty field selection. Inspect get_operation_schema selectableFields or official schema docs.');const document=o.operationShell.replace('%SELECTIONS%',rendered.selections);const ast=parse(document);const def=ast.definitions.find(d=>d.kind===Kind.OPERATION_DEFINITION) as OperationDefinitionNode;const variableNames=new Set((def.variableDefinitions??[]).map(v=>v.variable.name.value));const variables:Json={};if(variableNames.has('input'))variables.input=input;else{for(const k of variableNames)if(input[k]!==undefined)variables[k]=input[k];}
 if(o.pagination){variables[o.pagination.pageSizeArg]=args.first??o.pagination.defaultPageSize;if(args.after!==undefined)variables[o.pagination.cursorArg]=args.after;}return {document,variables};}
function genericDocument(document:string,expected:'query'|'mutation'):string{if(Buffer.byteLength(document)>65536)throw new UsageError('GraphQL document exceeds 64 KiB.');let ast:DocumentNode;try{ast=parse(document,{maxTokens:10000});}catch{throw new UsageError('Invalid GraphQL document.');}const ops=ast.definitions.filter(d=>d.kind===Kind.OPERATION_DEFINITION) as OperationDefinitionNode[];if(ops.length!==1||ops[0]!.operation!==expected||ast.definitions.some(d=>d.kind!==Kind.OPERATION_DEFINITION&&d.kind!==Kind.FRAGMENT_DEFINITION))throw new UsageError('Exactly one matching query or mutation operation is required; subscriptions and schema definitions are refused.');const op=ops[0]!;if(expected==='query')return print(ast);
 // Limit mutations to one direct root field: aliases are permitted, root fragments are not.
 if(op.selectionSet.selections.length!==1||op.selectionSet.selections[0]!.kind!==Kind.FIELD)throw new UsageError('Generic mutation requires one direct root field; split multi-action documents before confirming.');const field=op.selectionSet.selections[0] as FieldNode;if(field.name.value==='__typename'||!field.selectionSet)throw new UsageError('Generic mutation needs a result selection.');
 const selected:SelectionSetNode={kind:Kind.SELECTION_SET,selections:[...field.selectionSet.selections,{kind:Kind.FIELD,name:{kind:Kind.NAME,value:'__typename'}},{kind:Kind.INLINE_FRAGMENT,typeCondition:{kind:Kind.NAMED_TYPE,name:{kind:Kind.NAME,value:'MutationError'}},selectionSet:{kind:Kind.SELECTION_SET,selections:[{kind:Kind.FIELD,name:{kind:Kind.NAME,value:'message'}}]}}]};const replacement={...op,selectionSet:{...op.selectionSet,selections:[{...field,selectionSet:selected}]}};return print({...ast,definitions:ast.definitions.map(d=>d===op?replacement:d)});}
export const ALL_TOOLS:ToolSpec[]=OPERATIONS.map(o=>({name:toolName(o),title:o.description,description:`${o.description}. Current Buffer GraphQL ${o.fieldName}. ${o.operationType==='mutation'?'Requires explicit confirmation. ':'One request, no automatic pagination. '}Use upstream fields to bound data; provider errors are failures even with HTTP 200.`,group:o.group??'account',inputSchema:{type:'object',properties:propertiesFor(o),additionalProperties:false},risk:o.operationType==='query'?'read':'destructive',handler:async(args,client)=>{const {document,variables}=await prepare(o,args,client);const result=await client.request(document,variables,args.account);if(o.resultAccess.isUnion){const value=result.data[o.fieldName];if(!value||typeof value.__typename!=='string'||!o.resultAccess.successTypes.includes(value.__typename))throw new BufferError('Buffer returned an unrecognized mutation result; do not repeat without checking account state.',200,'INVALID_RESPONSE');}return result;}}));
ALL_TOOLS.push({name:'list_accounts',title:'List private account profile labels',description:'Local names, default marker and whether authentication is configured. No token, token path or organization ID.',group:'local',risk:'read',inputSchema:{type:'object',properties:{},additionalProperties:false},handler:async(_,c)=>({accounts:c.config.accounts.map(a=>({name:a.name,default:a.name===c.config.defaultAccount,authenticationConfigured:!!(a.apiToken||a.tokenFile)}))})});
for(const kind of ['query','mutation'] as const)ALL_TOOLS.push({name:'graphql_'+kind,title:'Run one GraphQL '+kind,description:kind==='query'?'One parsed GraphQL query; mutations and subscriptions are refused. Use explicit minimal selections. Current experimental APIs are accessible subject to provider availability.':'One parsed GraphQL mutation with one direct root field and explicit confirmation. Adds __typename and MutationError catch-all to detect HTTP 200 failures. No automatic retry.',group:'graphql',risk:kind==='query'?'read':'destructive',inputSchema:{type:'object',properties:{document:{type:'string',minLength:1,maxLength:65536},variables:{type:'object',description:'Native JSON variables; validated remotely by Buffer.'},account:accountSchema,...(kind==='mutation'?{confirm:confirmSchema}:{})},required:['document'],additionalProperties:false},handler:async(a,c)=>c.request(genericDocument(a.document,kind),a.variables??{},a.account)});
ALL_TOOLS.push({name:'preview_operation',title:'Preview a named operation locally',description:'Validate a current named input and upstream field selection, then return document and variables without credentials or a request. Does not validate permissions, assets or platform rules remotely. Operation names use native GraphQL camelCase.',group:'local',risk:'read',inputSchema:{type:'object',properties:{operation:{type:'string',enum:OPERATIONS.map(o=>o.fieldName)},arguments:{type:'object',description:'Arguments for that named tool. Provide all required native input, including organizationId; profile defaults are not read.'}},required:['operation','arguments'],additionalProperties:false},handler:async(a,c)=>{const o=OPERATIONS.find(o=>o.fieldName===a.operation)!;const tool=ALL_TOOLS.find(t=>t.name===toolName(o))!;validateArguments(tool,a.arguments);return {...await prepare(o,a.arguments,c,true),localOnly:true,providerValidated:false};}});
const paged=OPERATIONS.filter(o=>o.operationType==='query'&&o.pagination);
ALL_TOOLS.push({name:'query_pages',title:'Read bounded native cursor pages',description:'Read one to five pages of a schema-generated query. No mutations. Automatically includes hasNextPage/endCursor, stops on repeated or missing cursors and returns continuation state. API errors abort the remaining pages; no retries.',group:'pagination',risk:'read',inputSchema:{type:'object',properties:{operation:{type:'string',enum:paged.map(o=>o.fieldName)},arguments:{type:'object',description:'Arguments for the native read tool, including filters, fields, first/after and account.'},max_pages:{type:'integer',minimum:1,maximum:5,default:1}},required:['operation','arguments'],additionalProperties:false},handler:async(a,c)=>{const o=paged.find(o=>o.fieldName===a.operation)!;const tool=ALL_TOOLS.find(t=>t.name===toolName(o))!;validateArguments(tool,a.arguments);const args={...a.arguments,fields:[...new Set([...(a.arguments.fields??o.defaultFields),'pageInfo.hasNextPage','pageInfo.endCursor'])]};await prepare(o,args,c);const results:unknown[]=[];const seen=new Set<string>();if(args.after)seen.add(args.after);let after:string|undefined=args.after;let hasNextPage=false;for(let i=0;i<(a.max_pages??1);i++){const {document,variables}=await prepare(o,{...args,after},c);const result=await c.request(document,variables,args.account);results.push(result);const info=result.data[o.fieldName]?.pageInfo;if(!info||typeof info.hasNextPage!=='boolean')throw new UsageError('Buffer pagination response is missing pageInfo. Remaining pages were not requested.');hasNextPage=info.hasNextPage;if(!hasNextPage){after=undefined;break;}const next=info.endCursor;if(typeof next!=='string'||!next||seen.has(next))throw new UsageError('Buffer pagination returned a missing or repeated cursor. Remaining pages were not requested.');seen.add(next);after=next;}return {pages:results,pagesRead:results.length,hasNextPage,resumeCursor:after??null};}});
ALL_TOOLS.push({name:'get_operation_schema',title:'Inspect native input and selectable fields',description:'Local current operation input schema, every selectable upstream field path and bounded default selections. No credentials or request.',group:'local',risk:'read',inputSchema:{type:'object',properties:{operation:{type:'string',enum:OPERATIONS.map(o=>o.fieldName)}},required:['operation'],additionalProperties:false},handler:async a=>schemaForOperation(a.operation)});
const validators=new Map(ALL_TOOLS.map(t=>[t.name,ajv.compile(t.inputSchema)]));
export function validateArguments(tool:ToolSpec,args:unknown):void{check(validators.get(tool.name)!,args);}
export function visibleTools(config:Config):ToolSpec[]{return ALL_TOOLS.filter(t=>!config.readOnly||t.risk==='read');}
export function schemaForOperation(name:string):Json{const o=OPERATIONS.find(o=>o.fieldName===name);if(!o)throw new UsageError('Unknown Buffer operation.');return {input:o.jsonInputSchema??{},selectableFields:collectAllPaths(o.selectionTree),defaults:o.defaultFields};}
